//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterSignedPOReport
    {
        public int counterSignedId { get; set; }
        public string poReportId { get; set; }
        public string vendorId { get; set; }
    
        public virtual POReport POReport { get; set; }
        public virtual HTV_Vendor HTV_Vendor { get; set; }
    }
}
