//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryChallen
    {
        public string DC_ID { get; set; }
        public string DC_Number { get; set; }
        public string DC_Filename { get; set; }
        public string DC_Filesize { get; set; }
        public string InwardID { get; set; }
    
        public virtual InwardMaterial InwardMaterial { get; set; }
    }
}
