//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatePass
    {
        public GatePass()
        {
            this.OutMaterials = new HashSet<OutMaterial>();
            this.OutwardMaterials = new HashSet<OutwardMaterial>();
        }
    
        public string GatepassID { get; set; }
        public string Location { get; set; }
        public Nullable<int> userDepartmentId { get; set; }
        public string GatepassType { get; set; }
        public Nullable<bool> STP_Bonded_Item { get; set; }
        public string SenderID { get; set; }
        public string Reason { get; set; }
        public string Gatepass_Number { get; set; }
        public string ReceiverID { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverContact { get; set; }
        public string ReceiverEmail { get; set; }
        public Nullable<System.DateTime> Gatepass_DateTime { get; set; }
        public Nullable<System.DateTime> Expected_DateofReturn { get; set; }
        public string TO_Office { get; set; }
        public string From_Office { get; set; }
        public string GatePass_Category { get; set; }
        public string GatePass_Status { get; set; }
        public string Created_By { get; set; }
        public Nullable<bool> SEZ_Bonded_Item { get; set; }
        public string GatepassRejectReason { get; set; }
        public string Rejected_By { get; set; }
        public string GatepassFileName { get; set; }
        public string GatepassFileSize { get; set; }
        public string Gatepass_InvInchargeFileName { get; set; }
        public string Gatepass_InvInchargeFileSize { get; set; }
        public string Gatepass_SecurityGuardFileName { get; set; }
        public string Gatepass_SecurityGuardFileSize { get; set; }
        public string Approved_By { get; set; }
        public string Gatepass_DispatchBy { get; set; }
    
        public virtual ServiceUserDepartment ServiceUserDepartment { get; set; }
        public virtual ICollection<OutMaterial> OutMaterials { get; set; }
        public virtual ICollection<OutwardMaterial> OutwardMaterials { get; set; }
    }
}
