//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTV_Tokens
    {
        public string token_Id { get; set; }
        public string employeeId { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<System.DateTime> expire_time { get; set; }
        public string redirect_path { get; set; }
        public string type { get; set; }
        public string invoiceId { get; set; }
    }
}
