//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTV_Service
    {
        public HTV_Service()
        {
            this.CategoryExtraDocuments = new HashSet<CategoryExtraDocument>();
            this.CategoryExtraDocuments1 = new HashSet<CategoryExtraDocument>();
            this.HistoryServiceMaintenances = new HashSet<HistoryServiceMaintenance>();
            this.HTV_Invoice = new HashSet<HTV_Invoice>();
            this.HTV_Invoice1 = new HashSet<HTV_Invoice>();
            this.HTV_Sprint = new HashSet<HTV_Sprint>();
            this.POReports = new HashSet<POReport>();
            this.Req_Service = new HashSet<Req_Service>();
            this.POReports1 = new HashSet<POReport>();
            this.ServiceUsers = new HashSet<ServiceUser>();
            this.ServiceVendors = new HashSet<ServiceVendor>();
            this.HTV_Sprint1 = new HashSet<HTV_Sprint>();
            this.ServiceUsers1 = new HashSet<ServiceUser>();
            this.ServiceVendors1 = new HashSet<ServiceVendor>();
        }
    
        public string serviceCode { get; set; }
        public string details { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string vendorId { get; set; }
        public string serviceStatus { get; set; }
        public int serviceCategoryId { get; set; }
        public int serviceTypeId { get; set; }
        public string serviceValue { get; set; }
        public string billingUnit { get; set; }
        public string poNumber { get; set; }
        public int userDepartmentId { get; set; }
        public string subTypeOfService { get; set; }
        public string budgetValue { get; set; }
        public string document_type { get; set; }
        public string service_status { get; set; }
        public string service_delete_reason { get; set; }
        public string budgetRemarks { get; set; }
    
        public virtual ICollection<CategoryExtraDocument> CategoryExtraDocuments { get; set; }
        public virtual ICollection<CategoryExtraDocument> CategoryExtraDocuments1 { get; set; }
        public virtual ICollection<HistoryServiceMaintenance> HistoryServiceMaintenances { get; set; }
        public virtual ICollection<HTV_Invoice> HTV_Invoice { get; set; }
        public virtual ICollection<HTV_Invoice> HTV_Invoice1 { get; set; }
        public virtual ServiceUserDepartment ServiceUserDepartment { get; set; }
        public virtual ServiceUserDepartment ServiceUserDepartment1 { get; set; }
        public virtual ICollection<HTV_Sprint> HTV_Sprint { get; set; }
        public virtual ICollection<POReport> POReports { get; set; }
        public virtual ICollection<Req_Service> Req_Service { get; set; }
        public virtual ICollection<POReport> POReports1 { get; set; }
        public virtual HTV_Vendor HTV_Vendor { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual ICollection<ServiceUser> ServiceUsers { get; set; }
        public virtual ICollection<ServiceVendor> ServiceVendors { get; set; }
        public virtual ICollection<HTV_Sprint> HTV_Sprint1 { get; set; }
        public virtual ICollection<ServiceUser> ServiceUsers1 { get; set; }
        public virtual ICollection<ServiceVendor> ServiceVendors1 { get; set; }
    }
}
