//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTV_Sprint
    {
        public HTV_Sprint()
        {
            this.HTV_Invoice = new HashSet<HTV_Invoice>();
        }
    
        public string sprintId { get; set; }
        public string sprintName { get; set; }
        public string poReportId { get; set; }
        public string sprintValue { get; set; }
        public Nullable<System.DateTime> sprintEndDate { get; set; }
        public Nullable<System.DateTime> sprintCreateDate { get; set; }
        public string serviceCode { get; set; }
        public string sprint_status { get; set; }
        public string sprint_delete_reason { get; set; }
    
        public virtual ICollection<HTV_Invoice> HTV_Invoice { get; set; }
        public virtual HTV_Service HTV_Service { get; set; }
        public virtual HTV_Service HTV_Service1 { get; set; }
        public virtual POReport POReport { get; set; }
    }
}
