//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTV_Vendor_2092022
    {
        public string vendorId { get; set; }
        public string vendorName { get; set; }
        public string vendorAddress { get; set; }
        public string vendorEmail { get; set; }
        public string vendorPassword { get; set; }
        public string poc { get; set; }
        public string reason { get; set; }
        public Nullable<int> vendorCreditPeriod { get; set; }
        public string vendorStatus { get; set; }
        public string legalStatus { get; set; }
        public string businessNature { get; set; }
        public string establishmentRegNo { get; set; }
        public string establishmentRegNoCategory { get; set; }
        public string phoneNo { get; set; }
        public string mobileNo { get; set; }
        public string beneficiaryName { get; set; }
        public string bankName { get; set; }
        public string branchAddress { get; set; }
        public string accountNo { get; set; }
        public string IFSCCode { get; set; }
        public string PANNo { get; set; }
        public string TANNo { get; set; }
        public string ESICNo { get; set; }
        public string CSTNo { get; set; }
        public string PFNo { get; set; }
        public string ProfessionalTaxNo { get; set; }
        public string GSTNo { get; set; }
        public string vendorCode { get; set; }
        public Nullable<bool> registrationResult { get; set; }
        public string MsmeVendorRegistrationNo { get; set; }
        public string MSME_vendor_category { get; set; }
        public Nullable<System.DateTime> vendorRegistrationDate { get; set; }
        public string vendor_Reject_Reason { get; set; }
    }
}
