//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTV_Documents
    {
        public HTV_Documents()
        {
            this.VendorDocuments = new HashSet<VendorDocument>();
        }
    
        public string documentId { get; set; }
        public string typeOfDocument { get; set; }
        public Nullable<System.DateTime> documentDate { get; set; }
        public string documentIdentifier { get; set; }
        public string vendorId { get; set; }
        public string document_filename { get; set; }
        public string fileSize { get; set; }
    
        public virtual HTV_Vendor HTV_Vendor { get; set; }
        public virtual ICollection<VendorDocument> VendorDocuments { get; set; }
    }
}
