//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_Signature
    {
        public string IMSsignatureId { get; set; }
        public string categoryName { get; set; }
        public string referenceId { get; set; }
        public string role { get; set; }
        public string IMSsignaturePath { get; set; }
        public string userId { get; set; }
        public string IMSsignatureStatus { get; set; }
    
        public virtual IMSUser IMSUser { get; set; }
    }
}
