//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMSUser
    {
        public IMSUser()
        {
            this.GatepassApprovers = new HashSet<GatepassApprover>();
            this.IMSRoles = new HashSet<IMSRole>();
            this.InwardApprovers = new HashSet<InwardApprover>();
            this.IMS_Signature = new HashSet<IMS_Signature>();
        }
    
        public string userId { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public string userphone { get; set; }
        public string userStatus { get; set; }
        public string archiveduserReason { get; set; }
    
        public virtual ICollection<GatepassApprover> GatepassApprovers { get; set; }
        public virtual ICollection<IMSRole> IMSRoles { get; set; }
        public virtual ICollection<InwardApprover> InwardApprovers { get; set; }
        public virtual ICollection<IMS_Signature> IMS_Signature { get; set; }
    }
}
