//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_BKP_1012021
    {
        public string invoiceId { get; set; }
        public string employeeId { get; set; }
        public string vendorId { get; set; }
        public string sprintId { get; set; }
        public string serviceCode { get; set; }
        public string invoiceStatus { get; set; }
        public Nullable<System.DateTime> billingDate { get; set; }
        public string invoiceReason { get; set; }
        public string invoiceAmount { get; set; }
        public Nullable<System.DateTime> invoiceUploadDate { get; set; }
        public string uploadedBy { get; set; }
        public string invoiceNumber { get; set; }
        public Nullable<System.DateTime> approvedDate { get; set; }
        public Nullable<System.DateTime> paymentDueDate { get; set; }
        public Nullable<System.DateTime> invoiceProcessingDate { get; set; }
        public Nullable<System.DateTime> paymentProcessingDate { get; set; }
        public string invoiceFileName { get; set; }
        public string invoiceFileSize { get; set; }
        public string invoiceRejectReason { get; set; }
        public string invoiceProcessedBy { get; set; }
        public Nullable<bool> isPriorPayment { get; set; }
        public string approvalRemark { get; set; }
        public string location { get; set; }
        public string CompanyName { get; set; }
        public string ExpanseNature { get; set; }
        public string Nature_of_Business { get; set; }
        public string PaymentProcessedBy { get; set; }
        public string gstAmount { get; set; }
        public string mail_count { get; set; }
        public Nullable<System.DateTime> second_level_approved_date { get; set; }
        public Nullable<System.DateTime> First_level_approved_date { get; set; }
        public string CGST_amount { get; set; }
        public string SGST_amount { get; set; }
        public string total_Invoice_amount { get; set; }
        public string IGST_amount { get; set; }
        public string invoiceDeleteReason { get; set; }
    }
}
