//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Inventory_Register = new HashSet<Inventory_Register>();
            this.InwardMaterial_CAPEX = new HashSet<InwardMaterial_CAPEX>();
            this.InwardMaterial_OPEX = new HashSet<InwardMaterial_OPEX>();
            this.InwardMaterial_Rental = new HashSet<InwardMaterial_Rental>();
            this.InwardMaterial_CustomerAsset = new HashSet<InwardMaterial_CustomerAsset>();
        }
    
        public string MaterialID { get; set; }
        public string MaterialName { get; set; }
        public string MaterialDescription { get; set; }
        public string Material_Status { get; set; }
        public string MaterialPrefix { get; set; }
        public Nullable<int> Material_CategoryID { get; set; }
    
        public virtual ICollection<Inventory_Register> Inventory_Register { get; set; }
        public virtual ICollection<InwardMaterial_CAPEX> InwardMaterial_CAPEX { get; set; }
        public virtual ICollection<InwardMaterial_OPEX> InwardMaterial_OPEX { get; set; }
        public virtual ICollection<InwardMaterial_Rental> InwardMaterial_Rental { get; set; }
        public virtual Material_Category Material_Category { get; set; }
        public virtual ICollection<InwardMaterial_CustomerAsset> InwardMaterial_CustomerAsset { get; set; }
    }
}
