//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutwardMaterial
    {
        public string OW_MaterialID { get; set; }
        public string GatepassID { get; set; }
        public string OutwardNote { get; set; }
        public Nullable<System.DateTime> OutwardDatetime { get; set; }
        public string Outward_Status { get; set; }
        public string OutwardNo { get; set; }
    
        public virtual GatePass GatePass { get; set; }
    }
}
