//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTerm
    {
        public PaymentTerm()
        {
            this.POReports = new HashSet<POReport>();
            this.POReports1 = new HashSet<POReport>();
        }
    
        public int PaymentTermsId { get; set; }
        public string PaymentTerms { get; set; }
        public string CreditPeriod { get; set; }
    
        public virtual ICollection<POReport> POReports { get; set; }
        public virtual ICollection<POReport> POReports1 { get; set; }
    }
}
