//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class POReport
    {
        public POReport()
        {
            this.CounterSignedPOReports = new HashSet<CounterSignedPOReport>();
            this.HTV_Sprint = new HashSet<HTV_Sprint>();
            this.Signatures = new HashSet<Signature>();
        }
    
        public string poReportId { get; set; }
        public string poReportName { get; set; }
        public string vendorId { get; set; }
        public string poReportReason { get; set; }
        public string poReportStatus { get; set; }
        public string poReportValue { get; set; }
        public Nullable<System.DateTime> poReportDate { get; set; }
        public string serviceCode { get; set; }
        public string poFileName { get; set; }
        public string poFileSize { get; set; }
        public string HSPLpercent { get; set; }
        public string HILpercent { get; set; }
        public string HTVpercent { get; set; }
        public string HKPpercent { get; set; }
        public Nullable<int> hsplBillingAddressId { get; set; }
        public Nullable<int> hsplShippingAddressId { get; set; }
        public Nullable<int> hilplBillingAddressId { get; set; }
        public Nullable<int> hilplShippingAddressId { get; set; }
        public Nullable<int> htvBillingAddressId { get; set; }
        public Nullable<int> htvShippingAddressId { get; set; }
        public Nullable<int> hkpplBillingAddressId { get; set; }
        public Nullable<int> hkpplShippingAddressId { get; set; }
        public string poCreditPeriod { get; set; }
        public string Details { get; set; }
        public Nullable<int> PaymentTermsId { get; set; }
        public string po_delete_reason { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string Subject { get; set; }
        public string AdditionalClause { get; set; }
        public string QuotationNumber { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public Nullable<System.DateTime> ContractFromDate { get; set; }
        public Nullable<System.DateTime> ContractToDate { get; set; }
        public string deliverybox { get; set; }
        public string Tax_Details { get; set; }
        public string po_TLAFileName { get; set; }
        public string po_TLAFileSize { get; set; }
        public string po_FHFileName { get; set; }
        public string po_FHFileSize { get; set; }
    
        public virtual ICollection<CounterSignedPOReport> CounterSignedPOReports { get; set; }
        public virtual HTV_Service HTV_Service { get; set; }
        public virtual HTV_Service HTV_Service1 { get; set; }
        public virtual ICollection<HTV_Sprint> HTV_Sprint { get; set; }
        public virtual HTV_Vendor HTV_Vendor { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual PaymentTerm PaymentTerm1 { get; set; }
        public virtual ICollection<Signature> Signatures { get; set; }
    }
}
