//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req_Service
    {
        public int Req_ServiceID { get; set; }
        public string requisitionCode { get; set; }
        public string serviceCode { get; set; }
        public string req_service_relationstatus { get; set; }
    
        public virtual HTV_Service HTV_Service { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
