//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public Requisition()
        {
            this.Req_Service = new HashSet<Req_Service>();
        }
    
        public string requisitionCode { get; set; }
        public string requisitionIdentifier { get; set; }
        public System.DateTime dateOfRequisition { get; set; }
        public string raisedBy { get; set; }
        public string req_Department { get; set; }
        public string req_CompanyName { get; set; }
        public string req_DeliveryLocation { get; set; }
        public string req_ContactDetails { get; set; }
        public string budgeted_Comments { get; set; }
        public string req_status { get; set; }
        public string preparedBy { get; set; }
        public string checkedBy { get; set; }
        public string approvedBy { get; set; }
        public string productDetails { get; set; }
        public string Rec_vendor_name { get; set; }
        public string Rec_vendor_address { get; set; }
        public string Rec_vendor_contact_detail { get; set; }
        public string Rec_vendor_contact_person { get; set; }
        public string Req_Reject_Reason { get; set; }
        public string ComparisonSheet { get; set; }
        public string ComparisonSheet_size { get; set; }
        public Nullable<System.DateTime> Approved_by_date { get; set; }
        public string Evalution_note { get; set; }
        public string Payment_term { get; set; }
        public string negotiatedValue { get; set; }
        public string vendorProposedValue { get; set; }
        public string requisition_delete_reason { get; set; }
    
        public virtual ICollection<Req_Service> Req_Service { get; set; }
    }
}
