//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serial_Number
    {
        public int Serial_NumberId { get; set; }
        public Nullable<int> Serial_GRN_Number { get; set; }
        public string Location { get; set; }
        public string Year_Range { get; set; }
        public Nullable<int> Serial_Gatepass_Number { get; set; }
        public Nullable<int> Serial_Asset_Number { get; set; }
        public Nullable<int> Serial_Outward_Number { get; set; }
    }
}
