//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceUserDepartment
    {
        public ServiceUserDepartment()
        {
            this.GatepassApprovers = new HashSet<GatepassApprover>();
            this.GatePasses = new HashSet<GatePass>();
            this.HTV_Service = new HashSet<HTV_Service>();
            this.HTV_Service1 = new HashSet<HTV_Service>();
            this.IMSRoles = new HashSet<IMSRole>();
            this.InwardApprovers = new HashSet<InwardApprover>();
            this.InwardMaterials = new HashSet<InwardMaterial>();
            this.ServiceUsers = new HashSet<ServiceUser>();
            this.Users = new HashSet<User>();
        }
    
        public int userDepartmentId { get; set; }
        public string userDepartmentName { get; set; }
    
        public virtual ICollection<GatepassApprover> GatepassApprovers { get; set; }
        public virtual ICollection<GatePass> GatePasses { get; set; }
        public virtual ICollection<HTV_Service> HTV_Service { get; set; }
        public virtual ICollection<HTV_Service> HTV_Service1 { get; set; }
        public virtual ICollection<IMSRole> IMSRoles { get; set; }
        public virtual ICollection<InwardApprover> InwardApprovers { get; set; }
        public virtual ICollection<InwardMaterial> InwardMaterials { get; set; }
        public virtual ICollection<ServiceUser> ServiceUsers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
