//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceUser
    {
        public int serviceUserId { get; set; }
        public string serviceCode { get; set; }
        public string firstLevelApprover { get; set; }
        public string secondLevelApprover { get; set; }
        public string thirdLevelApprover { get; set; }
        public int userDepartmentId { get; set; }
    
        public virtual HTV_Service HTV_Service { get; set; }
        public virtual HTV_Service HTV_Service1 { get; set; }
        public virtual ServiceUserDepartment ServiceUserDepartment { get; set; }
    }
}
