//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceVMSEntities : DbContext
    {
        public ServiceVMSEntities()
            : base("name=ServiceVMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category_Number> Category_Number { get; set; }
        public DbSet<CategoryExtraDocument> CategoryExtraDocuments { get; set; }
        public DbSet<CounterSignedPOReport> CounterSignedPOReports { get; set; }
        public DbSet<DeliveryChallen> DeliveryChallens { get; set; }
        public DbSet<ExceptionLogger> ExceptionLoggers { get; set; }
        public DbSet<GatepassApprover> GatepassApprovers { get; set; }
        public DbSet<GatePass> GatePasses { get; set; }
        public DbSet<HistoryServiceMaintenance> HistoryServiceMaintenances { get; set; }
        public DbSet<HTV_Documents> HTV_Documents { get; set; }
        public DbSet<HTV_ForgotPasswordData> HTV_ForgotPasswordData { get; set; }
        public DbSet<HTV_Invoice> HTV_Invoice { get; set; }
        public DbSet<HTV_Login> HTV_Login { get; set; }
        public DbSet<HTV_Service> HTV_Service { get; set; }
        public DbSet<HTV_Sprint> HTV_Sprint { get; set; }
        public DbSet<HTV_Tokens> HTV_Tokens { get; set; }
        public DbSet<HTV_Vendor> HTV_Vendor { get; set; }
        public DbSet<HTV_VendorService> HTV_VendorService { get; set; }
        public DbSet<IMSExceptionLogger> IMSExceptionLoggers { get; set; }
        public DbSet<IMSRole> IMSRoles { get; set; }
        public DbSet<IMSUser> IMSUsers { get; set; }
        public DbSet<Inventory_Register> Inventory_Register { get; set; }
        public DbSet<InvoiceExtraDocument> InvoiceExtraDocuments { get; set; }
        public DbSet<InwardApprover> InwardApprovers { get; set; }
        public DbSet<InwardMaterial> InwardMaterials { get; set; }
        public DbSet<InwardMaterial_CAPEX> InwardMaterial_CAPEX { get; set; }
        public DbSet<InwardMaterial_OPEX> InwardMaterial_OPEX { get; set; }
        public DbSet<InwardMaterial_Rental> InwardMaterial_Rental { get; set; }
        public DbSet<InwardMaterial_Temp> InwardMaterial_Temp { get; set; }
        public DbSet<Material_Category> Material_Category { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<OfficeAddress> OfficeAddresses { get; set; }
        public DbSet<OutMaterial> OutMaterials { get; set; }
        public DbSet<OutwardMaterial> OutwardMaterials { get; set; }
        public DbSet<PaymentTerm> PaymentTerms { get; set; }
        public DbSet<POReport> POReports { get; set; }
        public DbSet<RejectedInvMaterial> RejectedInvMaterials { get; set; }
        public DbSet<Req_Service> Req_Service { get; set; }
        public DbSet<Requisition> Requisitions { get; set; }
        public DbSet<RequisitionApprover> RequisitionApprovers { get; set; }
        public DbSet<RequisitionExtraDoc> RequisitionExtraDocs { get; set; }
        public DbSet<Serial_Number> Serial_Number { get; set; }
        public DbSet<ServiceCategory> ServiceCategories { get; set; }
        public DbSet<ServiceDoccumentType> ServiceDoccumentTypes { get; set; }
        public DbSet<ServiceType> ServiceTypes { get; set; }
        public DbSet<ServiceUser> ServiceUsers { get; set; }
        public DbSet<ServiceUserDepartment> ServiceUserDepartments { get; set; }
        public DbSet<ServiceVendor> ServiceVendors { get; set; }
        public DbSet<Signature> Signatures { get; set; }
        public DbSet<Tax> Taxes { get; set; }
        public DbSet<TempVendor> TempVendors { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserFeedback> UserFeedbacks { get; set; }
        public DbSet<vendorAnnualTurnover> vendorAnnualTurnovers { get; set; }
        public DbSet<vendorCustomerReference> vendorCustomerReferences { get; set; }
        public DbSet<VendorDocument> VendorDocuments { get; set; }
        public DbSet<VendorReview> VendorReviews { get; set; }
        public DbSet<VendorServiceType> VendorServiceTypes { get; set; }
        public DbSet<vendorUnitAddress> vendorUnitAddresses { get; set; }
        public DbSet<HTV_Vendor_2092022> HTV_Vendor_2092022 { get; set; }
        public DbSet<Invoice_BKP_1012021> Invoice_BKP_1012021 { get; set; }
        public DbSet<InwardMaterial_CustomerAsset> InwardMaterial_CustomerAsset { get; set; }
        public DbSet<IMS_Signature> IMS_Signature { get; set; }
    }
}
