//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategory
    {
        public ServiceCategory()
        {
            this.HTV_Service = new HashSet<HTV_Service>();
        }
    
        public int serviceCategoryId { get; set; }
        public string categoryName { get; set; }
    
        public virtual ICollection<HTV_Service> HTV_Service { get; set; }
    }
}
