//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signature
    {
        public string signatureId { get; set; }
        public string categoryName { get; set; }
        public string referenceId { get; set; }
        public string role { get; set; }
        public string signaturePath { get; set; }
        public string employeeId { get; set; }
        public string signatureStatus { get; set; }
    
        public virtual POReport POReport { get; set; }
        public virtual User User { get; set; }
    }
}
