//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempVendor
    {
        public TempVendor()
        {
            this.InwardMaterials = new HashSet<InwardMaterial>();
        }
    
        public string TempVendorID { get; set; }
        public string TempVendorName { get; set; }
        public string TempVendorEmail { get; set; }
        public string TempVendorContact { get; set; }
        public string TempVendorAddress { get; set; }
        public string TempVendorStatus { get; set; }
        public string TempCategory { get; set; }
    
        public virtual ICollection<InwardMaterial> InwardMaterials { get; set; }
    }
}
