//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeedback
    {
        public string userfeedbackId { get; set; }
        public string employeeId { get; set; }
        public string user_Role { get; set; }
        public string user_Rating { get; set; }
        public string user_Comments { get; set; }
        public Nullable<int> userDepartmentId { get; set; }
        public System.DateTime userfeedbackaddeddate { get; set; }
    }
}
