//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.HTV_ForgotPasswordData = new HashSet<HTV_ForgotPasswordData>();
            this.HTV_Invoice = new HashSet<HTV_Invoice>();
            this.HTV_Invoice1 = new HashSet<HTV_Invoice>();
            this.ServiceDoccumentTypes = new HashSet<ServiceDoccumentType>();
            this.Signatures = new HashSet<Signature>();
            this.VendorReviews = new HashSet<VendorReview>();
        }
    
        public string employeeId { get; set; }
        public string userName { get; set; }
        public string designation { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public string phone { get; set; }
        public string archivedUserReason { get; set; }
        public string userStatus { get; set; }
        public int userDepartmentId { get; set; }
        public string userId { get; set; }
        public Nullable<bool> AccessinIMS { get; set; }
        public Nullable<bool> AccessinVMS { get; set; }
    
        public virtual ICollection<HTV_ForgotPasswordData> HTV_ForgotPasswordData { get; set; }
        public virtual ICollection<HTV_Invoice> HTV_Invoice { get; set; }
        public virtual ICollection<HTV_Invoice> HTV_Invoice1 { get; set; }
        public virtual ICollection<ServiceDoccumentType> ServiceDoccumentTypes { get; set; }
        public virtual ServiceUserDepartment ServiceUserDepartment { get; set; }
        public virtual ICollection<Signature> Signatures { get; set; }
        public virtual ICollection<VendorReview> VendorReviews { get; set; }
    }
}
