//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorServiceType
    {
        public VendorServiceType()
        {
            this.HTV_VendorService = new HashSet<HTV_VendorService>();
        }
    
        public int vendorServiceTypeId { get; set; }
        public string vendorServiceName { get; set; }
    
        public virtual ICollection<HTV_VendorService> HTV_VendorService { get; set; }
    }
}
