//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Number
    {
        public int CategoryNameId { get; set; }
        public Nullable<int> Category_PO_Number { get; set; }
        public Nullable<int> Category_Agreement_Number { get; set; }
        public Nullable<int> Category_letterOfIntent_Number { get; set; }
        public Nullable<int> Category_Addendum_Number { get; set; }
        public string Vendor_Code_Number { get; set; }
        public Nullable<int> Category_NoPO_Number { get; set; }
        public string Requisition_Identifier { get; set; }
        public string year_range { get; set; }
    }
}
