//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatepassApprover
    {
        public string GatepassApprover_Id { get; set; }
        public string Location { get; set; }
        public Nullable<int> userDepartmentId { get; set; }
        public string employeeId { get; set; }
        public string userEmail { get; set; }
        public string RoleInIMS { get; set; }
    
        public virtual IMSUser IMSUser { get; set; }
        public virtual ServiceUserDepartment ServiceUserDepartment { get; set; }
    }
}
