//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTV_Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HTV_Vendor()
        {
            this.CounterSignedPOReports = new HashSet<CounterSignedPOReport>();
            this.HTV_Documents = new HashSet<HTV_Documents>();
            this.HTV_ForgotPasswordData = new HashSet<HTV_ForgotPasswordData>();
            this.HTV_Invoice = new HashSet<HTV_Invoice>();
            this.HTV_Service = new HashSet<HTV_Service>();
            this.InwardMaterials = new HashSet<InwardMaterial>();
            this.POReports = new HashSet<POReport>();
            this.ServiceVendors = new HashSet<ServiceVendor>();
            this.vendorAnnualTurnovers = new HashSet<vendorAnnualTurnover>();
            this.vendorCustomerReferences = new HashSet<vendorCustomerReference>();
            this.VendorDocuments = new HashSet<VendorDocument>();
            this.VendorReviews = new HashSet<VendorReview>();
            this.HTV_VendorService = new HashSet<HTV_VendorService>();
            this.vendorUnitAddresses = new HashSet<vendorUnitAddress>();
        }
    
        public string vendorId { get; set; }
        public string vendorName { get; set; }
        public string vendorAddress { get; set; }
        public string vendorEmail { get; set; }
        public string vendorPassword { get; set; }
        public string poc { get; set; }
        public string reason { get; set; }
        public Nullable<int> vendorCreditPeriod { get; set; }
        public string vendorStatus { get; set; }
        public string legalStatus { get; set; }
        public string businessNature { get; set; }
        public string establishmentRegNo { get; set; }
        public string establishmentRegNoCategory { get; set; }
        public string phoneNo { get; set; }
        public string mobileNo { get; set; }
        public string beneficiaryName { get; set; }
        public string bankName { get; set; }
        public string branchAddress { get; set; }
        public string accountNo { get; set; }
        public string IFSCCode { get; set; }
        public string PANNo { get; set; }
        public string TANNo { get; set; }
        public string ESICNo { get; set; }
        public string CSTNo { get; set; }
        public string PFNo { get; set; }
        public string ProfessionalTaxNo { get; set; }
        public string GSTNo { get; set; }
        public string vendorCode { get; set; }
        public Nullable<bool> registrationResult { get; set; }
        public string MsmeVendorRegistrationNo { get; set; }
        public string MSME_vendor_category { get; set; }
        public Nullable<System.DateTime> vendorRegistrationDate { get; set; }
        public string vendor_Reject_Reason { get; set; }
        public int IsVendorLogin { get; set; }
        public bool IsTAVendor { get; set; }
        public string vendor_Active_Reason { get; set; }
        public Nullable<int> userDepartmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CounterSignedPOReport> CounterSignedPOReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTV_Documents> HTV_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTV_ForgotPasswordData> HTV_ForgotPasswordData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTV_Invoice> HTV_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTV_Service> HTV_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaterial> InwardMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POReport> POReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceVendor> ServiceVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendorAnnualTurnover> vendorAnnualTurnovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendorCustomerReference> vendorCustomerReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorDocument> VendorDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorReview> VendorReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTV_VendorService> HTV_VendorService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendorUnitAddress> vendorUnitAddresses { get; set; }
    }
}
