//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTV_Login
    {
        public int LoginId { get; set; }
        public string userEmail { get; set; }
        public int countAttempt { get; set; }
        public System.DateTime loginDatetime { get; set; }
    }
}
