//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMSExceptionLogger
    {
        public int exceptionId { get; set; }
        public string exceptionMessage { get; set; }
        public string controllerName { get; set; }
        public string actionName { get; set; }
        public string exceptionStackTrace { get; set; }
        public Nullable<System.DateTime> exceptionLogTime { get; set; }
    }
}
