//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMSRole
    {
        public string IMSRole_Id { get; set; }
        public string IMSuser_Id { get; set; }
        public int userDepartmentId { get; set; }
        public string RoleInIMS { get; set; }
        public string userLocation { get; set; }
        public string Role_Status { get; set; }
        public string Reason { get; set; }
    
        public virtual IMSUser IMSUser { get; set; }
        public virtual ServiceUserDepartment ServiceUserDepartment { get; set; }
    }
}
