//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Register
    {
        public string InventoryReg_ID { get; set; }
        public string AssetID { get; set; }
        public string MaterialID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Purchase_Rate { get; set; }
        public Nullable<double> Asset_Cost { get; set; }
        public string vendorId { get; set; }
        public string Make { get; set; }
        public string Serial_No { get; set; }
        public string GRN_Number { get; set; }
        public string Invoice_Number { get; set; }
        public string Location { get; set; }
        public string Alloted_To { get; set; }
        public Nullable<System.DateTime> Allot_date { get; set; }
        public string InwardID { get; set; }
        public string Inward_CP_Rental_ID { get; set; }
        public string ExpenseNature { get; set; }
        public string Model_Number { get; set; }
        public Nullable<int> Material_CategoryID { get; set; }
        public string IR_Status { get; set; }
        public Nullable<System.DateTime> AssetGenerateDate { get; set; }
        public string MachineID { get; set; }
        public string RAM { get; set; }
        public string HDD { get; set; }
        public string OS { get; set; }
        public Nullable<int> userDepartmentId { get; set; }
    
        public virtual Inventory_Register Inventory_Register1 { get; set; }
        public virtual Inventory_Register Inventory_Register2 { get; set; }
        public virtual Material_Category Material_Category { get; set; }
        public virtual Material Material { get; set; }
    }
}
