//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceExtraDocument
    {
        public string invoiceAdditionalId { get; set; }
        public string invoiceFileName { get; set; }
        public string invoiceFileSize { get; set; }
        public string invoiceTypeOfDoc { get; set; }
        public string invoiceId { get; set; }
        public string invoice_extra_doc_status { get; set; }
    
        public virtual HTV_Invoice HTV_Invoice { get; set; }
    }
}
