//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InwardMaterial()
        {
            this.DeliveryChallens = new HashSet<DeliveryChallen>();
            this.InwardMaterial_CAPEX = new HashSet<InwardMaterial_CAPEX>();
            this.InwardMaterial_OPEX = new HashSet<InwardMaterial_OPEX>();
            this.InwardMaterial_Rental = new HashSet<InwardMaterial_Rental>();
            this.InwardMaterial_CustomerAsset = new HashSet<InwardMaterial_CustomerAsset>();
        }
    
        public string InwardID { get; set; }
        public string vendorId { get; set; }
        public string GRN_Number { get; set; }
        public Nullable<System.DateTime> InwardDateTime { get; set; }
        public string InwardNote { get; set; }
        public string Inward_ExpenseNature { get; set; }
        public int userDepartmentId { get; set; }
        public string Location { get; set; }
        public string InwardEnteredBy { get; set; }
        public string BillofEntry { get; set; }
        public string Inward_Status { get; set; }
        public string TempVendorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryChallen> DeliveryChallens { get; set; }
        public virtual HTV_Vendor HTV_Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaterial_CAPEX> InwardMaterial_CAPEX { get; set; }
        public virtual InwardMaterial InwardMaterial1 { get; set; }
        public virtual InwardMaterial InwardMaterial2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaterial_OPEX> InwardMaterial_OPEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaterial_Rental> InwardMaterial_Rental { get; set; }
        public virtual ServiceUserDepartment ServiceUserDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaterial_CustomerAsset> InwardMaterial_CustomerAsset { get; set; }
        public virtual TempVendor TempVendor { get; set; }
    }
}
