//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionApprover
    {
        public string IT_approvers { get; set; }
        public string Non_IT_approvers { get; set; }
        public int ReqApproverNumber { get; set; }
    }
}
