//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceVMSEntities : DbContext
    {
        public ServiceVMSEntities()
            : base("name=ServiceVMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Number> Category_Number { get; set; }
        public virtual DbSet<CategoryExtraDocument> CategoryExtraDocuments { get; set; }
        public virtual DbSet<CounterSignedPOReport> CounterSignedPOReports { get; set; }
        public virtual DbSet<DeliveryChallen> DeliveryChallens { get; set; }
        public virtual DbSet<ExceptionLogger> ExceptionLoggers { get; set; }
        public virtual DbSet<GatepassApprover> GatepassApprovers { get; set; }
        public virtual DbSet<GatePass> GatePasses { get; set; }
        public virtual DbSet<HistoryServiceMaintenance> HistoryServiceMaintenances { get; set; }
        public virtual DbSet<HTV_Documents> HTV_Documents { get; set; }
        public virtual DbSet<HTV_ForgotPasswordData> HTV_ForgotPasswordData { get; set; }
        public virtual DbSet<HTV_Invoice> HTV_Invoice { get; set; }
        public virtual DbSet<HTV_Login> HTV_Login { get; set; }
        public virtual DbSet<HTV_Service> HTV_Service { get; set; }
        public virtual DbSet<HTV_Sprint> HTV_Sprint { get; set; }
        public virtual DbSet<HTV_Tokens> HTV_Tokens { get; set; }
        public virtual DbSet<HTV_Vendor> HTV_Vendor { get; set; }
        public virtual DbSet<HTV_VendorService> HTV_VendorService { get; set; }
        public virtual DbSet<IMSExceptionLogger> IMSExceptionLoggers { get; set; }
        public virtual DbSet<IMSRole> IMSRoles { get; set; }
        public virtual DbSet<IMSUser> IMSUsers { get; set; }
        public virtual DbSet<Inventory_Register> Inventory_Register { get; set; }
        public virtual DbSet<InvoiceExtraDocument> InvoiceExtraDocuments { get; set; }
        public virtual DbSet<InwardApprover> InwardApprovers { get; set; }
        public virtual DbSet<InwardMaterial> InwardMaterials { get; set; }
        public virtual DbSet<InwardMaterial_CAPEX> InwardMaterial_CAPEX { get; set; }
        public virtual DbSet<InwardMaterial_OPEX> InwardMaterial_OPEX { get; set; }
        public virtual DbSet<InwardMaterial_Rental> InwardMaterial_Rental { get; set; }
        public virtual DbSet<InwardMaterial_Temp> InwardMaterial_Temp { get; set; }
        public virtual DbSet<Material_Category> Material_Category { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<OfficeAddress> OfficeAddresses { get; set; }
        public virtual DbSet<OutMaterial> OutMaterials { get; set; }
        public virtual DbSet<OutwardMaterial> OutwardMaterials { get; set; }
        public virtual DbSet<PaymentTerm> PaymentTerms { get; set; }
        public virtual DbSet<POReport> POReports { get; set; }
        public virtual DbSet<RejectedInvMaterial> RejectedInvMaterials { get; set; }
        public virtual DbSet<Req_Service> Req_Service { get; set; }
        public virtual DbSet<Requisition> Requisitions { get; set; }
        public virtual DbSet<RequisitionApprover> RequisitionApprovers { get; set; }
        public virtual DbSet<RequisitionExtraDoc> RequisitionExtraDocs { get; set; }
        public virtual DbSet<Serial_Number> Serial_Number { get; set; }
        public virtual DbSet<ServiceCategory> ServiceCategories { get; set; }
        public virtual DbSet<ServiceDoccumentType> ServiceDoccumentTypes { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<ServiceUser> ServiceUsers { get; set; }
        public virtual DbSet<ServiceUserDepartment> ServiceUserDepartments { get; set; }
        public virtual DbSet<ServiceVendor> ServiceVendors { get; set; }
        public virtual DbSet<Signature> Signatures { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<TempVendor> TempVendors { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserFeedback> UserFeedbacks { get; set; }
        public virtual DbSet<vendorAnnualTurnover> vendorAnnualTurnovers { get; set; }
        public virtual DbSet<vendorCustomerReference> vendorCustomerReferences { get; set; }
        public virtual DbSet<VendorDocument> VendorDocuments { get; set; }
        public virtual DbSet<VendorReview> VendorReviews { get; set; }
        public virtual DbSet<VendorServiceType> VendorServiceTypes { get; set; }
        public virtual DbSet<vendorUnitAddress> vendorUnitAddresses { get; set; }
        public virtual DbSet<HTV_Vendor_2092022> HTV_Vendor_2092022 { get; set; }
        public virtual DbSet<Invoice_BKP_1012021> Invoice_BKP_1012021 { get; set; }
        public virtual DbSet<InwardMaterial_CustomerAsset> InwardMaterial_CustomerAsset { get; set; }
        public virtual DbSet<IMS_Signature> IMS_Signature { get; set; }
    }
}
