//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDoccumentType
    {
        public string serviceDocumentId { get; set; }
        public string employeeId { get; set; }
        public string user_email { get; set; }
        public string userDesignation { get; set; }
        public string documentType { get; set; }
    
        public virtual User User { get; set; }
    }
}
