//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TempVendor()
        {
            this.InwardMaterials = new HashSet<InwardMaterial>();
        }
    
        public string TempVendorID { get; set; }
        public string TempVendorName { get; set; }
        public string TempVendorEmail { get; set; }
        public string TempVendorContact { get; set; }
        public string TempVendorAddress { get; set; }
        public string TempVendorStatus { get; set; }
        public string TempCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaterial> InwardMaterials { get; set; }
    }
}
