//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendorCustomerReference
    {
        public int customerId { get; set; }
        public string customerName { get; set; }
        public string customerAddress { get; set; }
        public string CR_poc { get; set; }
        public string CR_phoneNo { get; set; }
        public string CR_email { get; set; }
        public string billingRange { get; set; }
        public string initialServiceYear { get; set; }
        public string vendorId { get; set; }
    
        public virtual HTV_Vendor HTV_Vendor { get; set; }
    }
}
