//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorReview
    {
        public string reviewId { get; set; }
        public string employeeId { get; set; }
        public string vendorId { get; set; }
        public string reviewText { get; set; }
        public string userDesignation { get; set; }
    
        public virtual HTV_Vendor HTV_Vendor { get; set; }
        public virtual User User { get; set; }
    }
}
