//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendorUnitAddress
    {
        public int UnitAddressId { get; set; }
        public string UnitAddress { get; set; }
        public string UA_poc { get; set; }
        public string UA_phoneNo { get; set; }
        public string UA_email { get; set; }
        public string vendorId { get; set; }
    
        public virtual HTV_Vendor HTV_Vendor { get; set; }
    }
}
